# -*- coding: utf-8 -*-
"""Enterprise Change Intelligence Platform Architecture.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-8nsG8cyuTG1bixP-_qDYmEKsTK2b_0g

# Enterprise Change Intelligence Platform
## AI-Powered Impact Analysis for ERP/Product Management

---

## 1. Executive Summary

This platform provides **AI-driven change impact analysis** for enterprise systems. It maintains a persistent knowledge base of enterprise artifacts (requirements, design docs, API specs, release notes) and uses semantic search + LLM analysis to:

* Analyze new business requirements
* Identify impacted modules, screens, APIs, reports, workflows
* Generate structured impact assessments with traceability
* Build enterprise memory for release intelligence

**Core Principles:**
* **Modularity**: Clean separation of concerns (ingestion, retrieval, analysis, UI)
* **Scalability**: Vector DB + chunking strategy for millions of documents
* **Extensibility**: Pluggable AI providers (Gemini/OpenAI/Claude/Databricks)
* **Traceability**: Source attribution for every insight
* **Enterprise-grade**: Metadata tracking, versioning, audit trail

---

## 2. High-Level Architecture

```
┌─────────────────────────────────────────────────────────────────┐
│                      STREAMLIT UI LAYER                         │
│  (Upload, Query, Results Visualization, Export)                 │
└────────────────┬───────────────────────────┬────────────────────┘
                 │                           │
                 ▼                           ▼
┌────────────────────────────┐  ┌──────────────────────────────┐
│  INGESTION SERVICE         │  │  QUERY & ANALYSIS SERVICE    │
│  - Document processor      │  │  - Semantic retriever        │
│  - Chunking engine         │  │  - Hybrid search             │
│  - Embedding generator     │  │  - LLM orchestrator          │
│  - Metadata extractor      │  │  - Impact analyzer           │
└────────────┬───────────────┘  └──────────┬───────────────────┘
             │                              │
             ▼                              ▼
┌─────────────────────────────────────────────────────────────────┐
│                   STORAGE LAYER                                  │
│  ┌──────────────────┐  ┌──────────────────┐  ┌──────────────┐  │
│  │ Vector DB        │  │ Metadata Store   │  │ Repository   │  │
│  │ (Databricks VS)  │  │ (Delta Tables)   │  │ (Local/S3)   │  │
│  └──────────────────┘  └──────────────────┘  └──────────────┘  │
└─────────────────────────────────────────────────────────────────┘
             │                              │
             ▼                              ▼
┌─────────────────────────────────────────────────────────────────┐
│                   AI PROVIDER LAYER                              │
│  (Abstraction over Gemini/OpenAI/Claude/Databricks Foundation)  │
└─────────────────────────────────────────────────────────────────┘
```

---

## 3. Technology Stack

### MVP Stack
| Component | Technology | Rationale |
|-----------|------------|----------|
| **UI Framework** | Streamlit | Rapid development, built-in components |
| **Vector DB** | Databricks Vector Search | Managed, scalable, Delta Lake integration |
| **Embeddings** | Databricks BGE/GTE models | No external API dependency, 1024-dim |
| **Storage** | Delta Lake (Unity Catalog) | ACID, versioning, metadata management |
| **Document Processing** | pypdf, python-docx, openpyxl | Lightweight, reliable |
| **Chunking** | LangChain TextSplitter | Proven, configurable |
| **LLM** | Databricks Foundation Model API | Unified interface (DBRX, Llama, external) |
| **Orchestration** | Python services | Simple, maintainable |

### Future Enhancements
| Component | Technology | Purpose |
|-----------|------------|----------|
| **Graph DB** | Neo4j | Dependency graphs, impact prediction |
| **Workflow** | Apache Airflow | Scheduled re-indexing, batch analysis |
| **Caching** | Redis | Query result caching |
| **Monitoring** | MLflow | RAG quality metrics, A/B testing |
| **UI** | React + FastAPI | Production-grade UI |

---

## 4. Folder Structure

```
enterprise-change-intelligence/
│
├── README.md
├── requirements.txt
├── .env.example
├── config/
│   ├── __init__.py
│   ├── settings.py              # Centralized configuration
│   ├── domains.yaml             # ERP domain definitions
│   └── embedding_config.yaml    # Embedding model settings
│
├── data/
│   ├── repository/              # Local enterprise repository (gitignored if large)
│   │   ├── ERP/
│   │   ├── Banking/
│   │   ├── Lending/
│   │   ├── Insurance/
│   │   ├── SupplyChain/
│   │   └── Finance/
│   └── uploads/                 # Temporary upload staging
│
├── src/
│   ├── __init__.py
│   │
│   ├── ingestion/
│   │   ├── __init__.py
│   │   ├── document_loader.py       # Multi-format document reader
│   │   ├── chunking_engine.py       # Text chunking strategies
│   │   ├── embedding_service.py     # Embedding generation
│   │   ├── metadata_extractor.py    # Extract doc metadata
│   │   └── repository_scanner.py    # Recursive folder indexing
│   │
│   ├── storage/
│   │   ├── __init__.py
│   │   ├── vector_store.py          # Vector DB interface
│   │   ├── metadata_store.py        # Delta table operations
│   │   └── repository_manager.py    # File system operations
│   │
│   ├── retrieval/
│   │   ├── __init__.py
│   │   ├── semantic_retriever.py    # Vector search
│   │   ├── hybrid_retriever.py      # Semantic + keyword
│   │   ├── reranker.py              # Result reranking
│   │   └── query_optimizer.py       # Query expansion/refinement
│   │
│   ├── analysis/
│   │   ├── __init__.py
│   │   ├── llm_orchestrator.py      # LLM provider abstraction
│   │   ├── impact_analyzer.py       # Core impact analysis logic
│   │   ├── prompt_templates.py      # Structured prompts
│   │   └── output_formatter.py      # Structure LLM outputs
│   │
│   ├── intelligence/                # Future: Advanced features
│   │   ├── __init__.py
│   │   ├── dependency_graph.py      # Module dependency mapping
│   │   ├── release_tracker.py       # Release history analysis
│   │   └── similarity_detector.py   # Duplicate requirement detection
│   │
│   └── utils/
│       ├── __init__.py
│       ├── logger.py                # Structured logging
│       ├── validators.py            # Input validation
│       └── exceptions.py            # Custom exceptions
│
├── ui/
│   ├── __init__.py
│   ├── app.py                       # Main Streamlit app
│   ├── pages/
│   │   ├── 1_📤_Upload.py
│   │   ├── 2_🔍_Query.py
│   │   ├── 3_📊_Analytics.py
│   │   └── 4_⚙️_Settings.py
│   └── components/
│       ├── __init__.py
│       ├── document_uploader.py
│       ├── query_interface.py
│       ├── results_viewer.py
│       └── export_handler.py
│
├── tests/
│   ├── __init__.py
│   ├── test_ingestion/
│   ├── test_retrieval/
│   ├── test_analysis/
│   └── fixtures/
│
├── notebooks/                       # Databricks notebooks for setup
│   ├── 01_setup_infrastructure.py
│   ├── 02_initial_indexing.py
│   └── 03_quality_evaluation.py
│
└── scripts/
    ├── setup_vector_search.py       # Initialize Vector Search
    ├── batch_indexing.py            # Bulk repository indexing
    └── migrate_metadata.py          # Schema migrations
```

## 5. Core Modules & Services

### 5.1 Ingestion Service

**Purpose:** Transform raw documents into searchable, semantically-indexed chunks.

| Component | Responsibility |
|-----------|---------------|
| **Document Loader** | Parse PDF/DOCX/PPTX/XLSX/TXT/JSON into text |
| **Chunking Engine** | Split text into semantic chunks (500-1000 tokens) with overlap |
| **Embedding Service** | Generate 1024-dim vectors via Databricks BGE/GTE |
| **Metadata Extractor** | Extract: doc_name, module, domain, release, upload_date, source_path, doc_type |
| **Repository Scanner** | Recursive folder traversal, change detection |

**Key Design Decisions:**
* **Chunking Strategy:** Hybrid approach - respect section boundaries (markdown headers, page breaks) while enforcing max token limits
* **Metadata Schema:** Store metadata both in Delta table AND as filters in Vector Search for fast filtering
* **Idempotency:** Track document hashes to avoid re-processing unchanged files

---

### 5.2 Storage Layer

**Purpose:** Durable, scalable storage for vectors, metadata, and raw documents.

| Store | Technology | Schema |
|-------|------------|--------|
| **Vector Store** | Databricks Vector Search (Storage-Optimized) | `doc_id, chunk_id, text, embedding, metadata` |
| **Metadata Store** | Delta Table (Unity Catalog) | `doc_id, doc_name, module, domain, release, upload_date, source_path, doc_type, chunk_count, status` |
| **Repository** | Local filesystem or S3 | Original documents in structured folders |

**Storage-Optimized vs Standard Endpoint:**
* Use **Storage-Optimized** for cost-effective storage (1B+ vectors, 7x cheaper, 300-500ms latency)
* Use **Standard** only if <100ms latency is critical

**Delta Table Schema for Metadata:**
```sql
CREATE TABLE IF NOT EXISTS main.change_intel.document_metadata (
  doc_id STRING PRIMARY KEY,
  doc_name STRING,
  module STRING,
  domain STRING,
  release STRING,
  upload_date TIMESTAMP,
  source_path STRING,
  doc_type STRING,
  chunk_count INT,
  status STRING,
  file_hash STRING,
  indexed_at TIMESTAMP
)
TBLPROPERTIES (
  delta.enableChangeDataFeed = true
);
```

---

### 5.3 Retrieval Service

**Purpose:** Find relevant context from enterprise knowledge base.

| Component | Approach |
|-----------|----------|
| **Semantic Retriever** | Pure vector similarity (ANN search) |
| **Hybrid Retriever** | Vector + BM25 keyword matching (best for technical terms, IDs, acronyms) |
| **Reranker** | Post-retrieval reranking using cross-encoder or LLM scoring |
| **Query Optimizer** | Query expansion, decomposition, domain-specific filtering |

**Retrieval Strategy:**
```
User Query → Query Optimizer (expand, add domain context)
           ↓
       Hybrid Search (top 50 chunks)
           ↓
       Reranker (top 10 chunks)
           ↓
       LLM Analysis
```

**When to Use Hybrid vs Semantic:**
* **Hybrid:** Queries with exact terms (error codes, API names, screen IDs, SKUs)
* **Semantic:** Natural language questions, conceptual queries

---

### 5.4 Analysis Service

**Purpose:** Generate structured impact analysis using LLM.

| Component | Responsibility |
|-----------|---------------|
| **LLM Orchestrator** | Abstract provider (Gemini/OpenAI/Claude/Databricks) |
| **Impact Analyzer** | Core logic: requirement → retrieval → LLM → structured output |
| **Prompt Templates** | Domain-specific prompts for each output type |
| **Output Formatter** | Parse LLM response into structured JSON |

**Output Structure:**
```json
{
  "requirement_summary": {
    "title": "...",
    "description": "...",
    "domain": "ERP",
    "priority": "High"
  },
  "impacted_modules": [
    {
      "module_name": "Order Management",
      "components": ["OrderScreen.tsx", "OrderAPI"],
      "impact_level": "High",
      "rationale": "...",
      "source_docs": ["doc1.pdf", "doc2.docx"]
    }
  ],
  "validation_changes": [
    {
      "test_type": "Unit",
      "test_scope": "OrderService.validateOrder()",
      "rationale": "..."
    }
  ],
  "regression_scope": [
    "Full order workflow",
    "Payment integration"
  ],
  "risks": [
    {
      "risk": "Data migration complexity",
      "severity": "High",
      "mitigation": "..."
    }
  ],
  "dependencies": [
    "Payment Gateway v2.1",
    "Inventory Service"
  ],
  "open_questions": [
    "How to handle legacy orders?",
    "Backward compatibility with v1 API?"
  ]
}
```

---

### 5.5 UI Layer (Streamlit)

**Pages:**

1. **Upload Page:** Drag-drop interface, metadata form (module, domain, release), batch upload support
2. **Query Page:** Natural language input, domain/module filters, result visualization with source links
3. **Analytics Page:** Usage metrics, most-queried modules, retrieval quality metrics
4. **Settings Page:** Repository path config, AI provider selection, embedding model config

**Key Features:**
* **Export:** JSON, Markdown, PDF reports
* **Traceability:** Click on any insight to see source chunks and documents
* **History:** Save query results for future reference

---

### 5.6 AI Provider Abstraction

**Purpose:** Support multiple LLM providers without code changes.

**Interface:**
```python
class BaseLLMProvider(ABC):
    @abstractmethod
    def generate(self, prompt: str, max_tokens: int, temperature: float) -> str:
        pass
    
    @abstractmethod
    def embed(self, texts: List[str]) -> List[List[float]]:
        pass
```

**Implementations:**
* `DatabricksProvider` (Foundation Model API)
* `GeminiProvider` (Google Gemini)
* `OpenAIProvider` (GPT-4)
* `ClaudeProvider` (Anthropic Claude)

**Configuration:**
```yaml
# config/settings.yaml
ai_providers:
  default: databricks
  databricks:
    endpoint: "databricks-dbrx-instruct"
    embedding_model: "databricks-gte-large-en"
  gemini:
    api_key: ${GEMINI_API_KEY}
    model: "gemini-1.5-pro"
```

## 6. Phased Implementation Plan

---

### Phase 1: MVP (Weeks 1-4)
**Goal:** Core RAG pipeline + basic UI for single-domain analysis

#### Week 1: Infrastructure Setup
* Set up Unity Catalog schema (`main.change_intel`)
* Create Vector Search endpoint (Storage-Optimized)
* Create Delta table for metadata
* Set up project structure and dependencies
* Configure Databricks authentication

**Deliverables:**
* Delta table: `main.change_intel.document_metadata`
* Delta table: `main.change_intel.document_chunks` (source for Vector Search)
* Vector Search endpoint: `change-intel-endpoint`
* Vector Search index: `main.change_intel.document_index`

#### Week 2: Ingestion Pipeline
* Implement document loaders (PDF, DOCX, TXT)
* Implement chunking engine (LangChain RecursiveCharacterTextSplitter)
* Implement embedding service (Databricks BGE)
* Implement repository scanner
* Create initial indexing script

**Deliverables:**
* `src/ingestion/` module complete
* Script: `scripts/batch_indexing.py`
* Indexed sample repository (100-500 docs)

#### Week 3: Retrieval + Analysis
* Implement semantic retrieval (Vector Search SDK)
* Implement LLM orchestrator (Databricks Foundation Model API)
* Implement impact analyzer with structured prompts
* Implement output formatter (JSON schema validation)

**Deliverables:**
* `src/retrieval/` module complete
* `src/analysis/` module complete
* End-to-end query → analysis pipeline working

#### Week 4: Streamlit UI
* Build Upload page (single file + metadata form)
* Build Query page (text input + results display)
* Build result export (JSON/Markdown)
* Basic error handling and logging

**Deliverables:**
* Working Streamlit app (`ui/app.py`)
* User can upload docs, query, view results, export

**MVP Scope:**
✅ Single ERP domain
✅ PDF, DOCX, TXT support
✅ Semantic search only
✅ Basic impact analysis output
✅ Manual upload workflow
✅ JSON/Markdown export

❌ Multi-domain support
❌ Hybrid search
❌ Reranking
❌ Dependency graphs
❌ Historical analysis
❌ Auto repository sync

---

### Phase 2: Multi-Domain + Enhanced Retrieval (Weeks 5-6)
**Goal:** Support all 6 domains + improve retrieval quality

#### Enhancements:
* Multi-domain metadata filtering
* Domain-specific prompt templates
* Hybrid search (semantic + BM25)
* PPTX, XLSX document support
* Query expansion and decomposition
* Reranking using cross-encoder

**Deliverables:**
* Support all 6 domains (ERP, Banking, Lending, Insurance, Supply Chain, Finance)
* Hybrid retrieval mode
* 20-30% improvement in retrieval quality (measured via eval set)

---

### Phase 3: Enterprise Features (Weeks 7-9)
**Goal:** Production-ready features for enterprise deployment

#### Enhancements:
* Auto repository sync (watch folders for changes)
* Batch upload via UI
* Advanced metadata extraction (auto-detect module, release from doc structure)
* Result history and comparison
* User authentication (Databricks SSO)
* Role-based access control
* Audit logging

**Deliverables:**
* Auto-sync daemon monitoring repository folders
* Batch upload UI (drag multiple files)
* User session management
* Audit trail in Delta table

---

### Phase 4: Intelligence Layer (Weeks 10-12)
**Goal:** Advanced analytics and predictive intelligence

#### Enhancements:
* Dependency graph generation (Neo4j integration)
* Module impact prediction (ML model)
* Similar requirement detection (clustering)
* Release history tracking and correlation
* Impact heatmaps (visual module impact over time)
* Automated regression scope generation

**Deliverables:**
* `src/intelligence/` module complete
* Neo4j dependency graph
* Similar requirement detector (cosine similarity + clustering)
* Release intelligence dashboard

---

### Phase 5: Production Hardening (Weeks 13-14)
**Goal:** Scalability, monitoring, and deployment

#### Enhancements:
* Async processing (Celery/Redis for long-running jobs)
* Query result caching
* MLflow integration (RAG quality metrics)
* Databricks Jobs for scheduled re-indexing
* Comprehensive unit/integration tests
* Performance benchmarking
* Documentation and runbooks

**Deliverables:**
* 95%+ test coverage
* <3s retrieval latency (p95)
* Scheduled re-indexing job (daily)
* MLflow experiment tracking
* Deployment guide

---

## 7. MVP vs Future State

### MVP Capabilities (Phase 1)
| Feature | Status | Description |
|---------|--------|-------------|
| Single domain analysis | ✅ | Focus on ERP domain only |
| PDF/DOCX/TXT support | ✅ | Core document types |
| Semantic search | ✅ | Pure vector similarity |
| Basic impact analysis | ✅ | Module identification, high-level risks |
| Manual upload | ✅ | Drag-drop interface |
| JSON/Markdown export | ✅ | Simple export formats |
| Databricks LLM only | ✅ | Single AI provider |

### Future State (Phases 2-5)
| Feature | Phase | Description |
|---------|-------|-------------|
| Multi-domain | 2 | All 6 domains with domain-specific prompts |
| Hybrid search | 2 | Semantic + keyword matching |
| PPTX/XLSX support | 2 | Additional document types |
| Reranking | 2 | Cross-encoder post-retrieval |
| Auto repository sync | 3 | Watch folders, auto-index changes |
| Batch upload | 3 | Multi-file upload |
| User auth + RBAC | 3 | Databricks SSO, role-based access |
| Dependency graphs | 4 | Neo4j-powered module relationships |
| Impact prediction | 4 | ML-based impact forecasting |
| Similar requirement detection | 4 | Duplicate/similar requirement finder |
| Release intelligence | 4 | Historical change correlation |
| Async processing | 5 | Celery for long-running jobs |
| MLflow monitoring | 5 | RAG quality tracking |
| Multi-provider AI | 5 | Gemini/OpenAI/Claude support |

---

## 8. Data Flow

### Indexing Flow
```
1. User uploads document OR Repository scanner detects new file
   ↓
2. Document Loader extracts text
   ↓
3. Metadata Extractor parses: module, domain, release, doc_type
   ↓
4. Chunking Engine splits into 500-1000 token chunks (with overlap)
   ↓
5. Embedding Service generates 1024-dim vectors (Databricks BGE/GTE)
   ↓
6. Write to Delta table: main.change_intel.document_chunks
   |
   ├── Columns: doc_id, chunk_id, text, module, domain, release, doc_type, source_path
   └── Vector Search auto-syncs and computes embeddings
   ↓
7. Update metadata table: main.change_intel.document_metadata
   └── Status: indexed, chunk_count, indexed_at
```

### Query Flow
```
1. User enters requirement text + optionally filters (domain, module, release)
   ↓
2. Query Optimizer: expand query, add domain context
   ↓
3. Hybrid Retrieval:
   ├── Vector Search: query_index() with filters
   └── Returns top 50 chunks with similarity scores
   ↓
4. Reranker (optional): Cross-encoder rescoring → top 10 chunks
   ↓
5. LLM Orchestrator:
   ├── Build prompt: system prompt + requirement + retrieved context
   ├── Call LLM (Databricks/Gemini/OpenAI/Claude)
   └── Parse structured output (JSON schema)
   ↓
6. Output Formatter: Validate and enrich output
   └── Add source document links, confidence scores
   ↓
7. Display in UI + Store in query history
```

---

## 9. Key Design Principles

1. **Modularity:** Each service is independently testable and replaceable
2. **Extensibility:** Add new document types, AI providers, or domains without core changes
3. **Traceability:** Every insight links back to source documents/chunks
4. **Idempotency:** Re-indexing same document is safe (hash-based deduplication)
5. **Scalability:** Storage-Optimized Vector Search handles 1B+ vectors
6. **Maintainability:** Clear separation of concerns, comprehensive logging
7. **Enterprise-grade:** Audit trails, RBAC, SSO integration in future phases

## 10. Implementation Examples

Below are production-ready code examples for core modules.
"""

# config/settings.py
"""Centralized configuration management using pydantic."""

from pydantic import BaseSettings, Field
from typing import Optional, List
import os

class VectorSearchConfig(BaseSettings):
    endpoint_name: str = "change-intel-endpoint"
    endpoint_type: str = "STORAGE_OPTIMIZED"  # or "STANDARD"
    index_name: str = "main.change_intel.document_index"
    embedding_dimension: int = 1024
    embedding_model: str = "databricks-gte-large-en"

class StorageConfig(BaseSettings):
    catalog: str = "main"
    schema: str = "change_intel"
    metadata_table: str = "document_metadata"
    chunks_table: str = "document_chunks"

class RepositoryConfig(BaseSettings):
    base_path: str = Field(default="/dbfs/mnt/enterprise-repo")
    upload_path: str = Field(default="/dbfs/mnt/uploads")
    supported_extensions: List[str] = [".pdf", ".docx", ".pptx", ".xlsx", ".txt"]
    auto_sync_enabled: bool = False

class ChunkingConfig(BaseSettings):
    chunk_size: int = 800  # tokens
    chunk_overlap: int = 100  # tokens
    separators: List[str] = ["\n\n", "\n", ". ", " ", ""]

class RetrievalConfig(BaseSettings):
    top_k: int = 50  # Initial retrieval
    rerank_top_k: int = 10  # After reranking
    use_hybrid: bool = True  # Semantic + keyword
    similarity_threshold: float = 0.7

class LLMConfig(BaseSettings):
    provider: str = "databricks"  # or "gemini", "openai", "claude"
    model_name: str = "databricks-dbrx-instruct"
    max_tokens: int = 4000
    temperature: float = 0.1
    timeout: int = 60

class DomainConfig(BaseSettings):
    supported_domains: List[str] = [
        "ERP", "Banking", "Lending", "Insurance", "SupplyChain", "Finance"
    ]

class Settings(BaseSettings):
    # Sub-configurations
    vector_search: VectorSearchConfig = VectorSearchConfig()
    storage: StorageConfig = StorageConfig()
    repository: RepositoryConfig = RepositoryConfig()
    chunking: ChunkingConfig = ChunkingConfig()
    retrieval: RetrievalConfig = RetrievalConfig()
    llm: LLMConfig = LLMConfig()
    domains: DomainConfig = DomainConfig()

    # General
    log_level: str = "INFO"
    debug_mode: bool = False

    class Config:
        env_file = ".env"
        env_file_encoding = "utf-8"
        case_sensitive = False

# Singleton instance
settings = Settings()

print("Configuration loaded successfully!")
print(f"Vector Search Endpoint: {settings.vector_search.endpoint_name}")
print(f"Storage: {settings.storage.catalog}.{settings.storage.schema}")
print(f"LLM Provider: {settings.llm.provider}")

# src/ingestion/document_loader.py
"""Multi-format document loader with metadata extraction."""

from abc import ABC, abstractmethod
from pathlib import Path
from typing import Dict, List, Optional
import hashlib
import mimetypes

# Document parsing libraries
try:
    from pypdf import PdfReader
    from docx import Document
    from pptx import Presentation
    from openpyxl import load_workbook
except ImportError:
    print("Install: pip install pypdf python-docx python-pptx openpyxl")

class DocumentLoader(ABC):
    """Base class for document loaders."""

    @abstractmethod
    def load(self, file_path: Path) -> Dict[str, any]:
        """Load document and return text + metadata."""
        pass

    def compute_hash(self, file_path: Path) -> str:
        """Compute SHA256 hash for deduplication."""
        sha256 = hashlib.sha256()
        with open(file_path, "rb") as f:
            for chunk in iter(lambda: f.read(8192), b""):
                sha256.update(chunk)
        return sha256.hexdigest()

class PDFLoader(DocumentLoader):
    """Load PDF documents."""

    def load(self, file_path: Path) -> Dict[str, any]:
        reader = PdfReader(str(file_path))
        text = ""
        for page in reader.pages:
            text += page.extract_text() + "\n\n"

        return {
            "text": text.strip(),
            "page_count": len(reader.pages),
            "metadata": reader.metadata or {},
            "file_hash": self.compute_hash(file_path)
        }

class DOCXLoader(DocumentLoader):
    """Load DOCX documents."""

    def load(self, file_path: Path) -> Dict[str, any]:
        doc = Document(str(file_path))
        text = "\n\n".join([para.text for para in doc.paragraphs if para.text.strip()])

        return {
            "text": text.strip(),
            "paragraph_count": len(doc.paragraphs),
            "metadata": doc.core_properties.__dict__,
            "file_hash": self.compute_hash(file_path)
        }

class PPTXLoader(DocumentLoader):
    """Load PPTX presentations."""

    def load(self, file_path: Path) -> Dict[str, any]:
        prs = Presentation(str(file_path))
        text = ""

        for slide in prs.slides:
            for shape in slide.shapes:
                if hasattr(shape, "text"):
                    text += shape.text + "\n"
            text += "\n"

        return {
            "text": text.strip(),
            "slide_count": len(prs.slides),
            "metadata": {},
            "file_hash": self.compute_hash(file_path)
        }

class XLSXLoader(DocumentLoader):
    """Load XLSX spreadsheets."""

    def load(self, file_path: Path) -> Dict[str, any]:
        wb = load_workbook(str(file_path), read_only=True)
        text = ""

        for sheet_name in wb.sheetnames:
            sheet = wb[sheet_name]
            text += f"\n\n=== Sheet: {sheet_name} ===\n\n"

            for row in sheet.iter_rows(values_only=True):
                row_text = "\t".join([str(cell) if cell is not None else "" for cell in row])
                if row_text.strip():
                    text += row_text + "\n"

        return {
            "text": text.strip(),
            "sheet_count": len(wb.sheetnames),
            "metadata": {},
            "file_hash": self.compute_hash(file_path)
        }

class TXTLoader(DocumentLoader):
    """Load plain text files."""

    def load(self, file_path: Path) -> Dict[str, any]:
        with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
            text = f.read()

        return {
            "text": text.strip(),
            "line_count": text.count("\n"),
            "metadata": {},
            "file_hash": self.compute_hash(file_path)
        }

class DocumentLoaderFactory:
    """Factory for creating appropriate document loader."""

    _loaders = {
        ".pdf": PDFLoader,
        ".docx": DOCXLoader,
        ".pptx": PPTXLoader,
        ".xlsx": XLSXLoader,
        ".txt": TXTLoader,
    }

    @classmethod
    def get_loader(cls, file_path: Path) -> DocumentLoader:
        """Get appropriate loader based on file extension."""
        ext = file_path.suffix.lower()
        loader_class = cls._loaders.get(ext)

        if loader_class is None:
            raise ValueError(f"Unsupported file type: {ext}")

        return loader_class()

    @classmethod
    def load_document(cls, file_path: Path) -> Dict[str, any]:
        """Load document using appropriate loader."""
        loader = cls.get_loader(file_path)
        result = loader.load(file_path)

        # Add common metadata
        result["file_name"] = file_path.name
        result["file_path"] = str(file_path)
        result["file_size"] = file_path.stat().st_size
        result["file_type"] = file_path.suffix.lower()[1:]  # Remove dot

        return result

# Example usage
if __name__ == "__main__":
    # Demo
    print("Document Loader Factory initialized!")
    print(f"Supported formats: {list(DocumentLoaderFactory._loaders.keys())}")

# src/storage/vector_store.py
"""Vector Search interface for document retrieval."""

from typing import List, Dict, Optional
from databricks.sdk import WorkspaceClient
from databricks.vector_search.client import VectorSearchClient
import json

class VectorStore:
    """Wrapper for Databricks Vector Search operations."""

    def __init__(
        self,
        endpoint_name: str,
        index_name: str,
        catalog: str,
        schema: str,
        chunks_table: str
    ):
        self.endpoint_name = endpoint_name
        self.index_name = index_name
        self.catalog = catalog
        self.schema = schema
        self.chunks_table = chunks_table

        self.workspace_client = WorkspaceClient()
        self.vs_client = VectorSearchClient()

    def create_endpoint(self, endpoint_type: str = "STORAGE_OPTIMIZED"):
        """Create Vector Search endpoint."""
        try:
            endpoint = self.workspace_client.vector_search_endpoints.create_endpoint(
                name=self.endpoint_name,
                endpoint_type=endpoint_type
            )
            print(f"Endpoint '{self.endpoint_name}' created successfully!")
            return endpoint
        except Exception as e:
            if "already exists" in str(e).lower():
                print(f"Endpoint '{self.endpoint_name}' already exists.")
            else:
                raise e

    def create_delta_sync_index(
        self,
        primary_key: str = "chunk_id",
        text_column: str = "text",
        embedding_model: str = "databricks-gte-large-en",
        pipeline_type: str = "TRIGGERED"
    ):
        """Create Delta Sync index with managed embeddings."""

        source_table = f"{self.catalog}.{self.schema}.{self.chunks_table}"

        try:
            index = self.workspace_client.vector_search_indexes.create_index(
                name=self.index_name,
                endpoint_name=self.endpoint_name,
                primary_key=primary_key,
                index_type="DELTA_SYNC",
                delta_sync_index_spec={
                    "source_table": source_table,
                    "embedding_source_columns": [
                        {
                            "name": text_column,
                            "embedding_model_endpoint_name": embedding_model
                        }
                    ],
                    "pipeline_type": pipeline_type
                }
            )
            print(f"Index '{self.index_name}' created successfully!")
            return index
        except Exception as e:
            if "already exists" in str(e).lower():
                print(f"Index '{self.index_name}' already exists.")
            else:
                raise e

    def sync_index(self):
        """Manually trigger index sync for TRIGGERED pipeline."""
        self.workspace_client.vector_search_indexes.sync_index(
            index_name=self.index_name
        )
        print(f"Index sync triggered for '{self.index_name}'.")

    def query(
        self,
        query_text: str,
        num_results: int = 50,
        filters: Optional[Dict[str, any]] = None,
        columns: Optional[List[str]] = None,
        query_type: str = "HYBRID"  # or "ANN"
    ) -> List[Dict[str, any]]:
        """Query the vector index.

        Args:
            query_text: Natural language query
            num_results: Number of results to return
            filters: Filter conditions (e.g., {"domain": "ERP", "module": "Order"})
            columns: Columns to return
            query_type: "HYBRID" (semantic + keyword) or "ANN" (semantic only)

        Returns:
            List of matching documents with scores
        """
        # For Storage-Optimized endpoints, use VectorSearchClient
        index = self.vs_client.get_index(
            endpoint_name=self.endpoint_name,
            index_name=self.index_name
        )

        # Build SQL-like filter string for Storage-Optimized
        filter_str = None
        if filters:
            conditions = []
            for key, value in filters.items():
                if isinstance(value, str):
                    conditions.append(f"{key} = '{value}'")
                elif isinstance(value, list):
                    values_str = ", ".join([f"'{v}'" for v in value])
                    conditions.append(f"{key} IN ({values_str})")
            filter_str = " AND ".join(conditions) if conditions else None

        # Default columns if not specified
        if columns is None:
            columns = ["chunk_id", "doc_id", "text", "module", "domain", "doc_name", "source_path"]

        # Execute search
        results = index.similarity_search(
            query_text=query_text,
            columns=columns,
            num_results=num_results,
            filters=filter_str,
            query_type=query_type
        )

        # Parse results
        documents = []
        if results and hasattr(results, 'get') and results.get('result', {}).get('data_array'):
            data_array = results['result']['data_array']

            for row in data_array:
                doc = {}
                for i, col in enumerate(columns):
                    doc[col] = row[i] if i < len(row) else None

                # Score is typically the last element
                doc["score"] = row[-1] if len(row) > len(columns) else None
                documents.append(doc)

        return documents

    def get_index_status(self) -> Dict[str, any]:
        """Get current index status."""
        index_info = self.workspace_client.vector_search_indexes.get_index(
            index_name=self.index_name
        )
        return {
            "name": index_info.name,
            "status": index_info.status,
            "index_type": index_info.index_type,
            "endpoint": index_info.endpoint_name
        }

# Example usage
if __name__ == "__main__":
    print("VectorStore class defined.")
    print("Ready for Vector Search operations!")

# src/analysis/llm_orchestrator.py
"""LLM provider abstraction for multi-provider support."""

from abc import ABC, abstractmethod
from typing import Dict, List, Optional
import json
import os

class BaseLLMProvider(ABC):
    """Base class for LLM providers."""

    @abstractmethod
    def generate(
        self,
        prompt: str,
        system_prompt: Optional[str] = None,
        max_tokens: int = 4000,
        temperature: float = 0.1,
        response_format: Optional[str] = None
    ) -> str:
        """Generate text completion."""
        pass

class DatabricksLLMProvider(BaseLLMProvider):
    """Databricks Foundation Model API provider."""

    def __init__(self, model_name: str = "databricks-dbrx-instruct", endpoint: Optional[str] = None):
        self.model_name = model_name
        self.endpoint = endpoint

        # Use Databricks SDK
        from databricks.sdk import WorkspaceClient
        self.client = WorkspaceClient()

    def generate(
        self,
        prompt: str,
        system_prompt: Optional[str] = None,
        max_tokens: int = 4000,
        temperature: float = 0.1,
        response_format: Optional[str] = None
    ) -> str:
        """Generate completion using Databricks Foundation Model API."""

        # Build messages
        messages = []
        if system_prompt:
            messages.append({"role": "system", "content": system_prompt})
        messages.append({"role": "user", "content": prompt})

        # Call API
        response = self.client.serving_endpoints.query(
            name=self.endpoint or self.model_name,
            messages=messages,
            max_tokens=max_tokens,
            temperature=temperature
        )

        return response.choices[0].message.content

class OpenAILLMProvider(BaseLLMProvider):
    """OpenAI API provider."""

    def __init__(self, model_name: str = "gpt-4", api_key: Optional[str] = None):
        self.model_name = model_name
        self.api_key = api_key or os.getenv("OPENAI_API_KEY")

        try:
            import openai
            self.client = openai.OpenAI(api_key=self.api_key)
        except ImportError:
            raise ImportError("Install OpenAI: pip install openai")

    def generate(
        self,
        prompt: str,
        system_prompt: Optional[str] = None,
        max_tokens: int = 4000,
        temperature: float = 0.1,
        response_format: Optional[str] = None
    ) -> str:
        messages = []
        if system_prompt:
            messages.append({"role": "system", "content": system_prompt})
        messages.append({"role": "user", "content": prompt})

        kwargs = {
            "model": self.model_name,
            "messages": messages,
            "max_tokens": max_tokens,
            "temperature": temperature
        }

        if response_format == "json":
            kwargs["response_format"] = {"type": "json_object"}

        response = self.client.chat.completions.create(**kwargs)
        return response.choices[0].message.content

class GeminiLLMProvider(BaseLLMProvider):
    """Google Gemini API provider."""

    def __init__(self, model_name: str = "gemini-1.5-pro", api_key: Optional[str] = None):
        self.model_name = model_name
        self.api_key = api_key or os.getenv("GEMINI_API_KEY")

        try:
            import google.generativeai as genai
            genai.configure(api_key=self.api_key)
            self.model = genai.GenerativeModel(self.model_name)
        except ImportError:
            raise ImportError("Install Gemini: pip install google-generativeai")

    def generate(
        self,
        prompt: str,
        system_prompt: Optional[str] = None,
        max_tokens: int = 4000,
        temperature: float = 0.1,
        response_format: Optional[str] = None
    ) -> str:
        # Gemini combines system prompt into user prompt
        full_prompt = prompt
        if system_prompt:
            full_prompt = f"{system_prompt}\n\n{prompt}"

        response = self.model.generate_content(
            full_prompt,
            generation_config={
                "max_output_tokens": max_tokens,
                "temperature": temperature
            }
        )
        return response.text

class LLMOrchestrator:
    """High-level LLM orchestration with provider abstraction."""

    _providers = {
        "databricks": DatabricksLLMProvider,
        "openai": OpenAILLMProvider,
        "gemini": GeminiLLMProvider,
    }

    def __init__(self, provider_name: str = "databricks", **provider_kwargs):
        provider_class = self._providers.get(provider_name.lower())
        if provider_class is None:
            raise ValueError(f"Unknown provider: {provider_name}. Available: {list(self._providers.keys())}")

        self.provider = provider_class(**provider_kwargs)
        self.provider_name = provider_name

    def generate(
        self,
        prompt: str,
        system_prompt: Optional[str] = None,
        max_tokens: int = 4000,
        temperature: float = 0.1,
        response_format: Optional[str] = None
    ) -> str:
        """Generate completion using configured provider."""
        return self.provider.generate(
            prompt=prompt,
            system_prompt=system_prompt,
            max_tokens=max_tokens,
            temperature=temperature,
            response_format=response_format
        )

    def generate_json(
        self,
        prompt: str,
        system_prompt: Optional[str] = None,
        max_tokens: int = 4000,
        temperature: float = 0.1
    ) -> Dict:
        """Generate JSON-formatted response."""
        response_text = self.generate(
            prompt=prompt,
            system_prompt=system_prompt,
            max_tokens=max_tokens,
            temperature=temperature,
            response_format="json"
        )

        # Parse JSON
        try:
            return json.loads(response_text)
        except json.JSONDecodeError:
            # Fallback: extract JSON from markdown code blocks
            if "```json" in response_text:
                start = response_text.find("```json") + 7
                end = response_text.find("```", start)
                response_text = response_text[start:end].strip()
            return json.loads(response_text)

# Example usage
if __name__ == "__main__":
    print("LLMOrchestrator class defined.")
    print(f"Supported providers: {list(LLMOrchestrator._providers.keys())}")

# src/analysis/impact_analyzer.py
"""Core impact analysis logic using RAG + LLM."""

from typing import Dict, List, Optional
import json

class ImpactAnalyzer:
    """Analyze business requirements and generate impact assessment."""

    def __init__(self, vector_store, llm_orchestrator):
        """
        Args:
            vector_store: VectorStore instance for retrieval
            llm_orchestrator: LLMOrchestrator instance for generation
        """
        self.vector_store = vector_store
        self.llm = llm_orchestrator

    def analyze_requirement(
        self,
        requirement_text: str,
        domain: Optional[str] = None,
        module: Optional[str] = None,
        top_k: int = 10
    ) -> Dict[str, any]:
        """Perform end-to-end impact analysis.

        Args:
            requirement_text: New business requirement description
            domain: Optional domain filter (e.g., "ERP", "Banking")
            module: Optional module filter (e.g., "OrderManagement")
            top_k: Number of relevant documents to retrieve

        Returns:
            Structured impact analysis as dict
        """

        # Step 1: Retrieve relevant context
        filters = {}
        if domain:
            filters["domain"] = domain
        if module:
            filters["module"] = module

        retrieved_docs = self.vector_store.query(
            query_text=requirement_text,
            num_results=top_k,
            filters=filters if filters else None,
            query_type="HYBRID"  # Semantic + keyword
        )

        if not retrieved_docs:
            return {
                "error": "No relevant documents found in the repository.",
                "suggestion": "Try broadening your search or checking domain/module filters."
            }

        # Step 2: Build context from retrieved docs
        context = self._build_context(retrieved_docs)

        # Step 3: Generate structured analysis
        analysis = self._generate_impact_analysis(requirement_text, context)

        # Step 4: Add source traceability
        analysis["sources"] = [
            {
                "doc_name": doc.get("doc_name"),
                "module": doc.get("module"),
                "source_path": doc.get("source_path"),
                "relevance_score": doc.get("score")
            }
            for doc in retrieved_docs[:5]  # Top 5 sources
        ]

        return analysis

    def _build_context(self, documents: List[Dict]) -> str:
        """Build context string from retrieved documents."""
        context_parts = []

        for i, doc in enumerate(documents, 1):
            doc_name = doc.get("doc_name", "Unknown")
            module = doc.get("module", "Unknown")
            text = doc.get("text", "")
            score = doc.get("score", 0.0)

            context_parts.append(
                f"[Document {i}: {doc_name} | Module: {module} | Relevance: {score:.2f}]\n{text}\n"
            )

        return "\n---\n".join(context_parts)

    def _generate_impact_analysis(self, requirement: str, context: str) -> Dict[str, any]:
        """Generate structured impact analysis using LLM."""

        system_prompt = """You are an expert enterprise change analyst specializing in impact assessment for ERP systems.

Your task is to analyze a new business requirement against existing enterprise documentation and provide a comprehensive impact analysis.

You MUST respond with a valid JSON object following this exact schema:
{
  "requirement_summary": {
    "title": "Brief title",
    "description": "Detailed description",
    "domain": "Domain name",
    "priority": "High/Medium/Low"
  },
  "impacted_modules": [
    {
      "module_name": "Module name",
      "components": ["Component1", "Component2"],
      "impact_level": "High/Medium/Low",
      "rationale": "Why this module is impacted",
      "source_docs": ["doc1.pdf", "doc2.docx"]
    }
  ],
  "validation_changes": [
    {
      "test_type": "Unit/Integration/E2E",
      "test_scope": "What needs testing",
      "rationale": "Why this testing is needed"
    }
  ],
  "regression_scope": ["Area 1", "Area 2"],
  "risks": [
    {
      "risk": "Risk description",
      "severity": "High/Medium/Low",
      "mitigation": "Mitigation strategy"
    }
  ],
  "dependencies": ["Dependency 1", "Dependency 2"],
  "open_questions": ["Question 1", "Question 2"]
}

Be specific, cite relevant information from the provided context, and ensure your analysis is actionable."""

        user_prompt = f"""**New Business Requirement:**
{requirement}

**Relevant Enterprise Documentation:**
{context}

**Instructions:**
Analyze the requirement against the provided documentation and generate a comprehensive impact analysis. Follow the JSON schema exactly."""

        # Generate JSON response
        try:
            analysis = self.llm.generate_json(
                prompt=user_prompt,
                system_prompt=system_prompt,
                max_tokens=4000,
                temperature=0.1
            )
            return analysis
        except Exception as e:
            return {
                "error": f"Failed to generate analysis: {str(e)}",
                "requirement": requirement
            }

    def export_markdown(self, analysis: Dict[str, any]) -> str:
        """Export analysis as markdown report."""
        md = []

        # Title
        req_summary = analysis.get("requirement_summary", {})
        md.append(f"# Impact Analysis: {req_summary.get('title', 'Untitled')}")
        md.append("")
        md.append(f"**Domain:** {req_summary.get('domain', 'N/A')}")
        md.append(f"**Priority:** {req_summary.get('priority', 'N/A')}")
        md.append("")

        # Description
        md.append("## Requirement Description")
        md.append(req_summary.get('description', 'N/A'))
        md.append("")

        # Impacted Modules
        md.append("## Impacted Modules")
        for module in analysis.get("impacted_modules", []):
            md.append(f"### {module.get('module_name')} ({module.get('impact_level')} Impact)")
            md.append(f"**Components:** {', '.join(module.get('components', []))}")
            md.append(f"**Rationale:** {module.get('rationale')}")
            md.append("")

        # Risks
        md.append("## Risks & Mitigations")
        for risk in analysis.get("risks", []):
            md.append(f"* **[{risk.get('severity')}]** {risk.get('risk')}")
            md.append(f"  * *Mitigation:* {risk.get('mitigation')}")
        md.append("")

        # Dependencies
        md.append("## Dependencies")
        for dep in analysis.get("dependencies", []):
            md.append(f"* {dep}")
        md.append("")

        # Open Questions
        md.append("## Open Questions")
        for question in analysis.get("open_questions", []):
            md.append(f"* {question}")
        md.append("")

        # Sources
        md.append("## Source Documents")
        for source in analysis.get("sources", []):
            md.append(f"* {source.get('doc_name')} (Module: {source.get('module')}, Relevance: {source.get('relevance_score', 0):.2f})")
        md.append("")

        return "\n".join(md)

# Example usage
if __name__ == "__main__":
    print("ImpactAnalyzer class defined.")
    print("Ready for requirement analysis!")

# ui/app.py
"""Main Streamlit application for Enterprise Change Intelligence Platform."""

import streamlit as st
from pathlib import Path
import json

# Page configuration
st.set_page_config(
    page_title="Enterprise Change Intelligence",
    page_icon="🔍",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom CSS
st.markdown("""
<style>
    .main-header {
        font-size: 2.5rem;
        font-weight: 700;
        color: #1F77B4;
        margin-bottom: 1rem;
    }
    .metric-card {
        background-color: #f0f2f6;
        padding: 1rem;
        border-radius: 0.5rem;
        border-left: 4px solid #1F77B4;
    }
    .source-doc {
        background-color: #e8f4f8;
        padding: 0.5rem;
        margin: 0.5rem 0;
        border-radius: 0.3rem;
        font-size: 0.9rem;
    }
</style>
""", unsafe_allow_html=True)

# Initialize session state
if "analysis_history" not in st.session_state:
    st.session_state.analysis_history = []
if "indexed_docs_count" not in st.session_state:
    st.session_state.indexed_docs_count = 0

# Sidebar
with st.sidebar:
    st.image("https://via.placeholder.com/200x80?text=Company+Logo", width=200)
    st.markdown("---")

    st.markdown("### 📊 Repository Stats")
    st.metric("Indexed Documents", st.session_state.indexed_docs_count)
    st.metric("Domains", 6)
    st.metric("Modules", "--")

    st.markdown("---")

    st.markdown("### ⚙️ Configuration")
    selected_domain = st.selectbox(
        "Domain Filter",
        ["All", "ERP", "Banking", "Lending", "Insurance", "SupplyChain", "Finance"]
    )

    selected_module = st.text_input("Module Filter (optional)")

    retrieval_mode = st.radio(
        "Retrieval Mode",
        ["Hybrid (Recommended)", "Semantic Only"],
        help="Hybrid combines vector similarity with keyword matching"
    )

    st.markdown("---")
    st.markdown("### 🔗 Quick Links")
    st.markdown("* [Documentation](#)")
    st.markdown("* [API Reference](#)")
    st.markdown("* [Support](#)")

# Main content
st.markdown('<div class="main-header">🔍 Enterprise Change Intelligence Platform</div>', unsafe_allow_html=True)
st.markdown("Analyze business requirements and identify impacted modules using AI-powered semantic search.")

st.markdown("---")

# Tabs
tab1, tab2, tab3, tab4 = st.tabs(["📤 Upload", "🔍 Analyze", "📜 History", "📊 Analytics"])

# ========== TAB 1: UPLOAD ==========
with tab1:
    st.header("📤 Upload Enterprise Documents")

    col1, col2 = st.columns([2, 1])

    with col1:
        uploaded_files = st.file_uploader(
            "Choose files",
            type=["pdf", "docx", "pptx", "xlsx", "txt"],
            accept_multiple_files=True,
            help="Upload requirements, design docs, API specs, release notes, etc."
        )

    with col2:
        st.markdown("### Metadata")
        upload_domain = st.selectbox("Domain *", ["ERP", "Banking", "Lending", "Insurance", "SupplyChain", "Finance"])
        upload_module = st.text_input("Module *", placeholder="e.g., OrderManagement")
        upload_release = st.text_input("Release", placeholder="e.g., v2.1.0")

    if uploaded_files:
        st.info(f"📁 {len(uploaded_files)} file(s) selected")

        if st.button("🚀 Upload & Index", type="primary", use_container_width=True):
            if not upload_module:
                st.error("Module is required!")
            else:
                with st.spinner("Processing documents..."):
                    # TODO: Implement actual upload + indexing logic
                    # For now, simulate
                    import time
                    progress_bar = st.progress(0)
                    for i, file in enumerate(uploaded_files):
                        time.sleep(0.5)  # Simulate processing
                        progress_bar.progress((i + 1) / len(uploaded_files))

                    st.session_state.indexed_docs_count += len(uploaded_files)
                    st.success(f"✅ Successfully indexed {len(uploaded_files)} document(s)!")
                    st.balloons()

# ========== TAB 2: ANALYZE ==========
with tab2:
    st.header("🔍 Analyze Business Requirement")

    requirement_text = st.text_area(
        "Enter your business requirement:",
        height=200,
        placeholder="""Example:
We need to add a new field 'Priority Level' to the order creation screen.
This field should be mandatory for enterprise customers and optional for standard customers.
The priority level should affect the order processing sequence in the fulfillment workflow.
"""
    )

    col1, col2, col3 = st.columns(3)
    with col1:
        num_sources = st.slider("Number of sources to retrieve", 5, 50, 10)
    with col2:
        include_risks = st.checkbox("Include risk analysis", value=True)
    with col3:
        include_regression = st.checkbox("Include regression scope", value=True)

    if st.button("🚀 Analyze Impact", type="primary", use_container_width=True):
        if not requirement_text:
            st.error("Please enter a business requirement!")
        else:
            with st.spinner("Analyzing requirement..."):
                # TODO: Implement actual analysis logic
                # For now, show mock result
                import time
                time.sleep(2)

                # Mock analysis result
                mock_analysis = {
                    "requirement_summary": {
                        "title": "Add Priority Level to Order Creation",
                        "description": requirement_text,
                        "domain": upload_domain if upload_domain else "ERP",
                        "priority": "High"
                    },
                    "impacted_modules": [
                        {
                            "module_name": "OrderManagement",
                            "components": ["OrderCreationScreen.tsx", "OrderAPI.java", "OrderService"],
                            "impact_level": "High",
                            "rationale": "New field requires UI changes, API modifications, and business logic updates",
                            "source_docs": ["OrderManagement_FSD_v2.0.pdf", "API_Spec_Orders.docx"]
                        },
                        {
                            "module_name": "Fulfillment",
                            "components": ["FulfillmentWorkflow", "PriorityQueue"],
                            "impact_level": "Medium",
                            "rationale": "Processing sequence logic needs to consider new priority field",
                            "source_docs": ["Fulfillment_Architecture.pdf"]
                        }
                    ],
                    "risks": [
                        {
                            "risk": "Backward compatibility with existing orders",
                            "severity": "High",
                            "mitigation": "Default priority level for existing orders without this field"
                        },
                        {
                            "risk": "Performance impact on order processing queue",
                            "severity": "Medium",
                            "mitigation": "Add database index on priority_level column"
                        }
                    ],
                    "dependencies": ["Customer Service v2.1", "Notification Service"],
                    "open_questions": [
                        "What are the valid priority levels (High/Medium/Low or numeric)?",
                        "Should priority level be editable after order creation?",
                        "How to handle priority conflicts between multiple orders?"
                    ],
                    "sources": [
                        {"doc_name": "OrderManagement_FSD_v2.0.pdf", "module": "OrderManagement", "relevance_score": 0.92},
                        {"doc_name": "API_Spec_Orders.docx", "module": "OrderManagement", "relevance_score": 0.87},
                        {"doc_name": "Fulfillment_Architecture.pdf", "module": "Fulfillment", "relevance_score": 0.78}
                    ]
                }

                # Display results
                st.success("✅ Analysis complete!")

                # Summary
                st.markdown("### 📋 Requirement Summary")
                col1, col2, col3 = st.columns(3)
                with col1:
                    st.metric("Domain", mock_analysis["requirement_summary"]["domain"])
                with col2:
                    st.metric("Priority", mock_analysis["requirement_summary"]["priority"])
                with col3:
                    st.metric("Impacted Modules", len(mock_analysis["impacted_modules"]))

                # Impacted Modules
                st.markdown("### 🎯 Impacted Modules")
                for module in mock_analysis["impacted_modules"]:
                    with st.expander(f"**{module['module_name']}** ({module['impact_level']} Impact)", expanded=True):
                        st.markdown(f"**Components:** {', '.join(module['components'])}")
                        st.markdown(f"**Rationale:** {module['rationale']}")
                        st.markdown(f"**Source Documents:** {', '.join(module['source_docs'])}")

                # Risks
                if include_risks:
                    st.markdown("### ⚠️ Risks & Mitigations")
                    for risk in mock_analysis["risks"]:
                        severity_color = {"High": "🔴", "Medium": "🟡", "Low": "🟢"}[risk["severity"]]
                        st.markdown(f"{severity_color} **{risk['risk']}**")
                        st.markdown(f"*Mitigation:* {risk['mitigation']}")
                        st.markdown("")

                # Dependencies
                st.markdown("### 🔗 Dependencies")
                st.markdown("\n".join([f"* {dep}" for dep in mock_analysis["dependencies"]]))

                # Open Questions
                st.markdown("### ❓ Open Questions")
                st.markdown("\n".join([f"* {q}" for q in mock_analysis["open_questions"]]))

                # Sources
                st.markdown("### 📚 Source Documents")
                for source in mock_analysis["sources"]:
                    st.markdown(
                        f'<div class="source-doc">'
                        f'📄 <strong>{source["doc_name"]}</strong> '
                        f'(Module: {source["module"]}, Relevance: {source["relevance_score"]:.0%})'
                        f'</div>',
                        unsafe_allow_html=True
                    )

                # Export options
                st.markdown("---")
                col1, col2, col3 = st.columns(3)
                with col1:
                    st.download_button(
                        "📥 Download JSON",
                        data=json.dumps(mock_analysis, indent=2),
                        file_name="impact_analysis.json",
                        mime="application/json",
                        use_container_width=True
                    )
                with col2:
                    # Mock markdown export
                    mock_md = "# Impact Analysis\n\nThis is a mock export."
                    st.download_button(
                        "📥 Download Markdown",
                        data=mock_md,
                        file_name="impact_analysis.md",
                        mime="text/markdown",
                        use_container_width=True
                    )
                with col3:
                    if st.button("💾 Save to History", use_container_width=True):
                        st.session_state.analysis_history.append({
                            "title": mock_analysis["requirement_summary"]["title"],
                            "analysis": mock_analysis
                        })
                        st.success("Saved to history!")

# ========== TAB 3: HISTORY ==========
with tab3:
    st.header("📜 Analysis History")

    if not st.session_state.analysis_history:
        st.info("No analysis history yet. Analyze a requirement to get started!")
    else:
        for i, item in enumerate(reversed(st.session_state.analysis_history)):
            with st.expander(f"#{len(st.session_state.analysis_history) - i}: {item['title']}"):
                st.json(item["analysis"])

# ========== TAB 4: ANALYTICS ==========
with tab4:
    st.header("📊 Platform Analytics")

    col1, col2, col3, col4 = st.columns(4)
    with col1:
        st.metric("Total Queries", "--")
    with col2:
        st.metric("Avg Response Time", "--")
    with col3:
        st.metric("Most Queried Module", "--")
    with col4:
        st.metric("Avg Sources/Query", "--")

    st.info("📈 Analytics dashboard coming in Phase 3!")

print("Streamlit UI skeleton complete!")

"""## 11. Setup & Deployment Instructions

---

### Prerequisites

1. **Databricks Workspace** (AWS/Azure/GCP)
   * Unity Catalog enabled
   * Serverless compute or cluster with DBR 14.3+
   * Vector Search feature enabled (contact Databricks if not available)

2. **Permissions**
   * `CREATE CATALOG` or access to existing catalog
   * `CREATE SCHEMA` privilege
   * Vector Search endpoint creation privilege
   * Databricks Foundation Model API access

3. **Local Environment** (for development)
   * Python 3.9+
   * pip or conda

---

### Step 1: Repository Setup

```bash
# Clone repository structure
mkdir enterprise-change-intelligence
cd enterprise-change-intelligence

# Create folder structure (use the structure from Section 4)
mkdir -p config data/repository data/uploads src/{ingestion,storage,retrieval,analysis,intelligence,utils} ui/{pages,components} tests notebooks scripts

# Initialize git
git init

# Create virtual environment
python -m venv venv
source venv/bin/activate  # On Windows: venv\Scripts\activate

# Install dependencies
pip install -r requirements.txt
```

---

### Step 2: Configure Environment

**Create `.env` file:**
```bash
# Databricks
DATABRICKS_HOST=https://your-workspace.cloud.databricks.com
DATABRICKS_TOKEN=dapi...

# Storage
CATALOG=main
SCHEMA=change_intel

# Vector Search
VECTOR_SEARCH_ENDPOINT=change-intel-endpoint
EMBEDDING_MODEL=databricks-gte-large-en

# LLM
LLM_PROVIDER=databricks
LLM_MODEL=databricks-dbrx-instruct

# Optional: External AI providers
# OPENAI_API_KEY=sk-...
# GEMINI_API_KEY=...
# ANTHROPIC_API_KEY=...

# Repository
REPOSITORY_PATH=/dbfs/mnt/enterprise-repo
UPLOAD_PATH=/dbfs/mnt/uploads
```

**Create `requirements.txt`:**
```txt
# Core
python-dotenv==1.0.0
pydantic==2.5.0
pydantic-settings==2.1.0

# Databricks
databricks-sdk==0.20.0
databricks-vectorsearch==0.23

# Document Processing
pypdf==3.17.0
python-docx==1.1.0
python-pptx==0.6.23
openpyxl==3.1.2

# Text Processing
langchain==0.1.0
langchain-community==0.0.10

# UI
streamlit==1.30.0

# Optional: External AI providers
openai==1.10.0  # Optional
google-generativeai==0.3.0  # Optional
anthropic==0.8.0  # Optional

# Utilities
requests==2.31.0
tqdm==4.66.0
```

---

### Step 3: Initialize Databricks Infrastructure

**Run this notebook on Databricks:**

```python
# notebooks/01_setup_infrastructure.py

from databricks.sdk import WorkspaceClient
import os

# Configuration
CATALOG = "main"
SCHEMA = "change_intel"
ENDPOINT_NAME = "change-intel-endpoint"

w = WorkspaceClient()

# 1. Create catalog (if needed)
try:
    spark.sql(f"CREATE CATALOG IF NOT EXISTS {CATALOG}")
    print(f"✅ Catalog '{CATALOG}' ready")
except Exception as e:
    print(f"⚠️ Catalog creation: {e}")

# 2. Create schema
spark.sql(f"CREATE SCHEMA IF NOT EXISTS {CATALOG}.{SCHEMA}")
print(f"✅ Schema '{CATALOG}.{SCHEMA}' created")

# 3. Create metadata table
spark.sql(f'''
CREATE TABLE IF NOT EXISTS {CATALOG}.{SCHEMA}.document_metadata (
  doc_id STRING PRIMARY KEY,
  doc_name STRING,
  module STRING,
  domain STRING,
  release STRING,
  upload_date TIMESTAMP,
  source_path STRING,
  doc_type STRING,
  chunk_count INT,
  status STRING,
  file_hash STRING,
  indexed_at TIMESTAMP
)
TBLPROPERTIES (
  delta.enableChangeDataFeed = true
)
''')
print(f"✅ Table '{CATALOG}.{SCHEMA}.document_metadata' created")

# 4. Create chunks table (source for Vector Search)
spark.sql(f'''
CREATE TABLE IF NOT EXISTS {CATALOG}.{SCHEMA}.document_chunks (
  chunk_id STRING PRIMARY KEY,
  doc_id STRING,
  text STRING,
  doc_name STRING,
  module STRING,
  domain STRING,
  release STRING,
  doc_type STRING,
  source_path STRING,
  chunk_index INT,
  created_at TIMESTAMP
)
TBLPROPERTIES (
  delta.enableChangeDataFeed = true
)
''')
print(f"✅ Table '{CATALOG}.{SCHEMA}.document_chunks' created")

# 5. Create Vector Search endpoint
try:
    endpoint = w.vector_search_endpoints.create_endpoint(
        name=ENDPOINT_NAME,
        endpoint_type="STORAGE_OPTIMIZED"
    )
    print(f"✅ Vector Search endpoint '{ENDPOINT_NAME}' created")
except Exception as e:
    if "already exists" in str(e).lower():
        print(f"✅ Vector Search endpoint '{ENDPOINT_NAME}' already exists")
    else:
        raise e

# 6. Create Vector Search index
try:
    index = w.vector_search_indexes.create_index(
        name=f"{CATALOG}.{SCHEMA}.document_index",
        endpoint_name=ENDPOINT_NAME,
        primary_key="chunk_id",
        index_type="DELTA_SYNC",
        delta_sync_index_spec={
            "source_table": f"{CATALOG}.{SCHEMA}.document_chunks",
            "embedding_source_columns": [
                {
                    "name": "text",
                    "embedding_model_endpoint_name": "databricks-gte-large-en"
                }
            ],
            "pipeline_type": "TRIGGERED"
        }
    )
    print(f"✅ Vector Search index '{CATALOG}.{SCHEMA}.document_index' created")
except Exception as e:
    if "already exists" in str(e).lower():
        print(f"✅ Vector Search index already exists")
    else:
        raise e

print("\n🎉 Infrastructure setup complete!")
```

---

### Step 4: Initial Repository Indexing

**Run batch indexing script:**

```python
# scripts/batch_indexing.py

import sys
sys.path.append('../src')

from pathlib import Path
from ingestion.document_loader import DocumentLoaderFactory
from ingestion.chunking_engine import ChunkingEngine
from storage.vector_store import VectorStore
import uuid
from datetime import datetime

# Configuration
REPOSITORY_PATH = Path("/dbfs/mnt/enterprise-repo")
CATALOG = "main"
SCHEMA = "change_intel"

# Initialize services
vector_store = VectorStore(
    endpoint_name="change-intel-endpoint",
    index_name=f"{CATALOG}.{SCHEMA}.document_index",
    catalog=CATALOG,
    schema=SCHEMA,
    chunks_table="document_chunks"
)

chunker = ChunkingEngine(chunk_size=800, chunk_overlap=100)

# Scan and index
for file_path in REPOSITORY_PATH.rglob("*"):
    if file_path.is_file() and file_path.suffix.lower() in [".pdf", ".docx", ".pptx", ".xlsx", ".txt"]:
        try:
            print(f"Processing: {file_path.name}")
            
            # Load document
            doc_data = DocumentLoaderFactory.load_document(file_path)
            
            # Generate chunks
            chunks = chunker.chunk_text(doc_data["text"])
            
            # Prepare rows for Delta table
            doc_id = str(uuid.uuid4())
            rows = []
            
            for i, chunk in enumerate(chunks):
                rows.append({
                    "chunk_id": f"{doc_id}_chunk_{i}",
                    "doc_id": doc_id,
                    "text": chunk,
                    "doc_name": doc_data["file_name"],
                    "module": "Auto-Detected",  # TODO: Implement auto-detection
                    "domain": "General",
                    "release": "--",
                    "doc_type": doc_data["file_type"],
                    "source_path": str(file_path),
                    "chunk_index": i,
                    "created_at": datetime.now()
                })
            
            # Write to Delta table
            from pyspark.sql import SparkSession
            spark = SparkSession.builder.getOrCreate()
            df = spark.createDataFrame(rows)
            df.write.mode("append").saveAsTable(f"{CATALOG}.{SCHEMA}.document_chunks")
            
            print(f"  ✅ Indexed {len(chunks)} chunks")
            
        except Exception as e:
            print(f"  ❌ Error: {e}")

print("\n🎉 Batch indexing complete!")
print("Run: vector_store.sync_index() to trigger Vector Search sync")
```

---

### Step 5: Launch Streamlit UI

```bash
# From project root
streamlit run ui/app.py
```

Access at: `http://localhost:8501`

---

### Step 6: (Optional) Deploy to Databricks Apps

**For production deployment:**

1. Package application as Databricks App
2. Configure app with Databricks authentication
3. Set up scheduled re-indexing job
4. Enable monitoring and logging

*(Detailed deployment guide in Phase 5)*

---

## 12. Execution Roadmap

### Week 1: Infrastructure (MVP Phase 1)
* Day 1-2: Set up Unity Catalog schema, create Delta tables
* Day 3-4: Create Vector Search endpoint and index
* Day 5: Test infrastructure with sample documents

### Week 2: Ingestion Pipeline
* Day 1-2: Implement document loaders (PDF, DOCX, TXT)
* Day 3-4: Implement chunking and embedding pipeline
* Day 5: Test end-to-end ingestion with 50-100 docs

### Week 3: Retrieval & Analysis
* Day 1-2: Implement semantic retrieval
* Day 3-4: Implement LLM orchestrator and impact analyzer
* Day 5: Test query → analysis pipeline

### Week 4: UI Development
* Day 1-2: Build Streamlit upload page
* Day 3-4: Build query and results pages
* Day 5: Testing, bug fixes, documentation

### Weeks 5-14: Future Phases
* Follow phased implementation plan (Section 6)
* Iterative development with user feedback
* Continuous quality improvement

---

## 13. Success Metrics

### MVP (Phase 1)
* ✅ System can index 500+ documents
* ✅ Retrieval latency <5s (p95)
* ✅ Semantic relevance >70% (manual eval on 50 queries)
* ✅ UI fully functional for single-domain analysis
* ✅ Export works for JSON and Markdown

### Production (Phase 5)
* ✅ System can handle 10,000+ documents
* ✅ Retrieval latency <3s (p95)
* ✅ Semantic relevance >85%
* ✅ Multi-domain support with domain-specific prompts
* ✅ 95%+ test coverage
* ✅ User authentication and RBAC
* ✅ Scheduled re-indexing automated

---

## 14. Next Steps

**Immediate Actions:**

1. **Review & Approve Architecture**
   * Stakeholder sign-off on design
   * Budget approval for Databricks resources

2. **Set Up Development Environment**
   * Clone repository structure
   * Configure Databricks workspace
   * Run infrastructure setup notebook

3. **Start MVP Development**
   * Begin Week 1 tasks
   * Set up daily standups
   * Create project board (Jira/GitHub Projects)

4. **Prepare Sample Data**
   * Collect 50-100 representative documents
   * Organize into domain/module folders
   * Define metadata schema

5. **Define Evaluation Criteria**
   * Create 20-50 test queries with expected results
   * Establish quality benchmarks
   * Plan user acceptance testing

**Questions to Address:**

1. What is the initial repository size? (# of documents, total GB)
2. How frequently will new documents be added?
3. Who are the primary users? (PMs, Developers, QA, Business Analysts)
4. Are there existing taxonomy/metadata standards?
5. What are the compliance/security requirements?

---

**This architecture provides a solid foundation for building a scalable, enterprise-grade AI-powered Change Intelligence Platform. The modular design ensures maintainability and extensibility as requirements evolve.**
"""